services:

  # Base de datos MySQL
  notecloud-mysql-db:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    container_name: notecloud-mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: notecloud
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    ports:
      - ${DB_MYSQL_PORT_PUBLIC}:3306
    volumes:
      - notecloud-mysql-data:/var/lib/mysql
    networks:
      notecloud-network:
        ipv4_address: 173.21.0.250
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Adminer
  mysql-adminer-bd:
    image: adminer
    container_name: mysql-adminer-bd-container
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - notecloud-mysql-db
    networks:
      notecloud-network:
        ipv4_address: 173.21.0.253

  notecloud-app:
    build: .
    container_name: notecloud-app-container
    restart: unless-stopped
    depends_on:
      - notecloud-mysql-db
    environment:
      DB_HOST: notecloud-mysql-db
      DB_PORT: 3306
      DB_NAME: notecloud
      DB_USER: notecloudUser
      DB_PWD: admin@987
    ports:
      - 9081:9081   # HTTP
      - 9444:9444   # HTTPS
    volumes:
      - .:/workspace
    networks:
      notecloud-network:
        ipv4_address: 173.21.0.100
    env_file:
      - src/main/liberty/config/server.env

networks:
  notecloud-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.21.0.0/24

volumes:
  notecloud-mysql-data:
    name: notecloud-mysql-data-local
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_MYSQL_DATA_DIR_BD}
      o: bind
